spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/customer_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: sha
    password: root
